### ISSUE TITLE
hey , just a question!

### ISSUE THREAD

**Issue by Maureks** [Marttins011/mt-chopshop#1]
Does it check if the player owns the vehicle?

Thanks !

**Comment by Marttins011** [comment]
No, this is for rob npc cars and then destroy them

**Comment by Maureks** [comment]
The thing is , if you buy a car , store it , then take it out , and scrap it , you kinda have a loop , of infinite money , the player then goes to wherever the car is stored , takes it out again , and then scraps it again , and so on 
Or doe it not happen like this?

**Comment by Marttins011** [comment]
Yeah, you're rigth xD i'll try to fix this...

**Comment by Maureks** [comment]
whenever you do it , just say so , i'll be glad to give it a go :) 
thanks for the attention !
